// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxAvzqr9y3Dxn1IzHS6yCW7dFhhaTF9qg',
    appId: '1:688545440183:web:3113730bff59754b11c832',
    messagingSenderId: '688545440183',
    projectId: 'codelabmodul3-27578',
    authDomain: 'codelabmodul3-27578.firebaseapp.com',
    storageBucket: 'codelabmodul3-27578.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCodcTz1Wtz3nNKtwuf1MbxIWxWbTQ6Dz0',
    appId: '1:688545440183:android:889f54ab61aadced11c832',
    messagingSenderId: '688545440183',
    projectId: 'codelabmodul3-27578',
    storageBucket: 'codelabmodul3-27578.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCveKOnpEtSey85adRD7zYRjyGqU00Ip1Q',
    appId: '1:688545440183:ios:e3d5eaafd77768a311c832',
    messagingSenderId: '688545440183',
    projectId: 'codelabmodul3-27578',
    storageBucket: 'codelabmodul3-27578.appspot.com',
    iosBundleId: 'com.example.codelabmodul3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCveKOnpEtSey85adRD7zYRjyGqU00Ip1Q',
    appId: '1:688545440183:ios:e3d5eaafd77768a311c832',
    messagingSenderId: '688545440183',
    projectId: 'codelabmodul3-27578',
    storageBucket: 'codelabmodul3-27578.appspot.com',
    iosBundleId: 'com.example.codelabmodul3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxAvzqr9y3Dxn1IzHS6yCW7dFhhaTF9qg',
    appId: '1:688545440183:web:58b06d645911fd9311c832',
    messagingSenderId: '688545440183',
    projectId: 'codelabmodul3-27578',
    authDomain: 'codelabmodul3-27578.firebaseapp.com',
    storageBucket: 'codelabmodul3-27578.appspot.com',
  );

}